In [1]:
import numpy as np
import pandas as pd

# Numpy

In [9]:
# Gere um array 5x5 de números inteiros aleatórios entre 10 e 99.

array = np.random.randint(10, 100, (5, 5))
print(array)

[[34 34 89 79 94]
 [20 90 76 25 70]
 [58 59 28 50 33]
 [81 52 70 38 28]
 [92 14 95 97 60]]


In [10]:
# Substitua os valores da diagonal principal por -1 sem usar laços for ou while.

np.fill_diagonal(array, -1)
print(array)

[[-1 34 89 79 94]
 [20 -1 76 25 70]
 [58 59 -1 50 33]
 [81 52 70 -1 28]
 [92 14 95 97 -1]]


In [ ]:
# Dado um array 1D com 100 elementos aleatórios entre 1 e 1000, substitua todos os múltiplos de 3 por -1 

array = np.random.randint(1, 1001, 100)
array[array % 3 == 0] = -1
print(array)

In [11]:
# Crie dois arrays 3x3 de números inteiros aleatórios entre 1 e 50. 

array1 = np.random.randint(1, 51, (3, 3))
array2 = np.random.randint(1, 51, (3, 3))
print(array1)
print(array2)

[[ 5 37 16]
 [27 49 29]
 [28 39 14]]
[[19 43  3]
 [36  6 20]
 [50 14 27]]


In [12]:
# Eleve todos os elementos do primeiro array ao quadrado e divida pelos elementos do segundo array (evitando divisões por zero). 

array2[array2 == 0] = 1 
result = np.divide(np.square(array1), array2)
print(result)

[[  1.31578947  31.8372093   85.33333333]
 [ 20.25       400.16666667  42.05      ]
 [ 15.68       108.64285714   7.25925926]]


In [16]:
# Gere uma matriz quadrada 4x4 aleatória e encontre sua matriz inversa. Caso não seja invertível, gere outra matriz até que seja.

while True:
    try:
        array = np.random.rand(4, 4)
        inv = np.linalg.inv(array)
        break
    except np.linalg.LinAlgError:
        pass
print(array)
print(inv)

[[0.77282786 0.65033683 0.30125494 0.06993038]
 [0.98293003 0.57628106 0.43116221 0.31234509]
 [0.70373897 0.51281191 0.37067484 0.15183583]
 [0.47491445 0.90494837 0.63817731 0.47036581]]
[[ 0.22398603  1.55117074 -0.35025793 -0.95028653]
 [ 4.16886038 -0.08024073 -5.22113838  1.11889226]
 [-6.33587136 -5.07752378 14.24102779 -0.28337241]
 [ 0.34958263  5.47722793 -8.92304975  1.31728732]]


In [17]:
# Crie uma matriz 10x10 de zeros e substitua os elementos do "perímetro" por 1 (sem usar loops explícitos). 

array = np.zeros((10, 10))
array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# Pandas

In [31]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows")

csv_path = path + "/imdb_top_1000.csv"

print("Path to dataset files:", path)

Path to dataset files: /home/mxs2/.cache/kagglehub/datasets/harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows/versions/1


In [37]:
# Mostre as 5 primeiras e 5 últimas linhas.

df = pd.read_csv(csv_path)
df

Poster_Link  \
0    https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1    https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2    https://m.media-amazon.com/images/M/MV5BMTMxNT...   
3    https://m.media-amazon.com/images/M/MV5BMWMwMG...   
4    https://m.media-amazon.com/images/M/MV5BMWU4N2...   
..                                                 ...   
995  https://m.media-amazon.com/images/M/MV5BNGEwMT...   
996  https://m.media-amazon.com/images/M/MV5BODk3Yj...   
997  https://m.media-amazon.com/images/M/MV5BM2U3Yz...   
998  https://m.media-amazon.com/images/M/MV5BZTBmMj...   
999  https://m.media-amazon.com/images/M/MV5BMTY5OD...   

                 Series_Title Released_Year Certificate  Runtime  \
0    The Shawshank Redemption          1994           A  142 min   
1               The Godfather          1972           A  175 min   
2             The Dark Knight          2008          UA  152 min   
3      The Godfather: Part II          1974           A  202 min   
4                12 Angry Men          1957           U   96 min   
..                        ...           ...         ...      ...   
995    Breakfast at Tiffany's          1961           A  115 min   
996                     Giant          1956           G  201 min   
997     From Here to Eternity          1953      Passed  118 min   
998                  Lifeboat          1944         NaN   97 min   
999              The 39 Steps          1935         NaN   86 min   

                        Genre  IMDB_Rating  \
0                       Drama          9.3   
1                Crime, Drama          9.2   
2        Action, Crime, Drama          9.0   
3                Crime, Drama          9.0   
4                Crime, Drama          9.0   
..                        ...          ...   
995    Comedy, Drama, Romance          7.6   
996            Drama, Western          7.6   
997       Drama, Romance, War          7.6   
998                Drama, War          7.6   
999  Crime, Mystery, Thriller          7.6   

                                              Overview  Meta_score  \
0    Two imprisoned men bond over a number of years...        80.0   
1    An organized crime dynasty's aging patriarch t...       100.0   
2    When the menace known as the Joker wreaks havo...        84.0   
3    The early life and career of Vito Corleone in ...        90.0   
4    A jury holdout attempts to prevent a miscarria...        96.0   
..                                                 ...         ...   
995  A young New York socialite becomes interested ...        76.0   
996  Sprawling epic covering the life of a Texas ca...        84.0   
997  In Hawaii in 1941, a private is cruelly punish...        85.0   
998  Several survivors of a torpedoed merchant ship...        78.0   
999  A man in London tries to help a counter-espion...        93.0   

                 Director              Star1              Star2  \
0          Frank Darabont        Tim Robbins     Morgan Freeman   
1    Francis Ford Coppola      Marlon Brando          Al Pacino   
2       Christopher Nolan     Christian Bale       Heath Ledger   
3    Francis Ford Coppola          Al Pacino     Robert De Niro   
4            Sidney Lumet        Henry Fonda        Lee J. Cobb   
..                    ...                ...                ...   
995         Blake Edwards     Audrey Hepburn     George Peppard   
996        George Stevens   Elizabeth Taylor        Rock Hudson   
997        Fred Zinnemann     Burt Lancaster   Montgomery Clift   
998      Alfred Hitchcock  Tallulah Bankhead        John Hodiak   
999      Alfred Hitchcock       Robert Donat  Madeleine Carroll   

              Star3           Star4  No_of_Votes        Gross  
0        Bob Gunton  William Sadler      2343110   28,341,469  
1        James Caan    Diane Keaton      1620367  134,966,411  
2     Aaron Eckhart   Michael Caine      2303232  534,858,444  
3     Robert Duvall    Diane Keaton      1129952   57,300,000  
4     Mart

In [41]:
# Exiba informações sobre os dados (info(), describe(), shape()

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Poster_Link    1000 non-null   object 
 1   Series_Title   1000 non-null   object 
 2   Released_Year  1000 non-null   object 
 3   Certificate    899 non-null    object 
 4   Runtime        1000 non-null   object 
 5   Genre          1000 non-null   object 
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object 
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object 
 10  Star1          1000 non-null   object 
 11  Star2          1000 non-null   object 
 12  Star3          1000 non-null   object 
 13  Star4          1000 non-null   object 
 14  No_of_Votes    1000 non-null   int64  
 15  Gross          831 non-null    object 
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB
None


In [42]:
df.describe()

IMDB_Rating  Meta_score   No_of_Votes
count  1000.000000  843.000000  1.000000e+03
mean      7.949300   77.971530  2.736929e+05
std       0.275491   12.376099  3.273727e+05
min       7.600000   28.000000  2.508800e+04
25%       7.700000   70.000000  5.552625e+04
50%       7.900000   79.000000  1.385485e+05
75%       8.100000   87.000000  3.741612e+05
max       9.300000  100.000000  2.343110e+06

In [46]:
df.shape

(1000, 16)

In [47]:
# Identifique quais colunas contêm valores ausentes. 

df.isnull().sum()

Poster_Link        0
Series_Title       0
Released_Year      0
Certificate      101
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score       157
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross            169
dtype: int64

In [52]:
# Filtre apenas os registros onde uma determinada coluna tem valores acima da média da própria coluna. 

column = "IMDB_Rating"

df[df[column] > df[column].mean()]

Poster_Link  \
0    https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1    https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2    https://m.media-amazon.com/images/M/MV5BMTMxNT...   
3    https://m.media-amazon.com/images/M/MV5BMWMwMG...   
4    https://m.media-amazon.com/images/M/MV5BMWU4N2...   
..                                                 ...   
458  https://m.media-amazon.com/images/M/MV5BNjUyMT...   
459  https://m.media-amazon.com/images/M/MV5BYTE4Nj...   
460  https://m.media-amazon.com/images/M/MV5BYmFlOW...   
461  https://m.media-amazon.com/images/M/MV5BMzg2MW...   
462  https://m.media-amazon.com/images/M/MV5BMTEyMT...   

                       Series_Title Released_Year Certificate  Runtime  \
0          The Shawshank Redemption          1994           A  142 min   
1                     The Godfather          1972           A  175 min   
2                   The Dark Knight          2008          UA  152 min   
3            The Godfather: Part II          1974           A  202 min   
4                      12 Angry Men          1957           U   96 min   
..                              ...           ...         ...      ...   
458                The Wizard of Oz          1939           U  102 min   
459                 La règle du jeu          1939         NaN  110 min   
460                    The Thin Man          1934       TV-PG   91 min   
461  All Quiet on the Western Front          1930           U  152 min   
462            Bronenosets Potemkin          1925         NaN   75 min   

                          Genre  IMDB_Rating  \
0                         Drama          9.3   
1                  Crime, Drama          9.2   
2          Action, Crime, Drama          9.0   
3                  Crime, Drama          9.0   
4                  Crime, Drama          9.0   
..                          ...          ...   
458  Adventure, Family, Fantasy          8.0   
459               Comedy, Drama          8.0   
460      Comedy, Crime, Mystery          8.0   
461                  Drama, War          8.0   
462    Drama, History, Thriller          8.0   

                                              Overview  Meta_score  \
0    Two imprisoned men bond over a number of years...        80.0   
1    An organized crime dynasty's aging patriarch t...       100.0   
2    When the menace known as the Joker wreaks havo...        84.0   
3    The early life and career of Vito Corleone in ...        90.0   
4    A jury holdout attempts to prevent a miscarria...        96.0   
..                                                 ...         ...   
458  Dorothy Gale is swept away from a farm in Kans...        92.0   
459  A bourgeois life in France at the onset of Wor...         NaN   
460  Former detective Nick Charles and his wealthy ...        86.0   
461  A German youth eagerly enters World War I, but...        91.0   
462  In the midst of the Russian Revolution of 1905...        97.0   

                 Director              Star1             Star2  \
0          Frank Darabont        Tim Robbins    Morgan Freeman   
1    Francis Ford Coppola      Marlon Brando         Al Pacino   
2       Christopher Nolan     Christian Bale      Heath Ledger   
3    Francis Ford Coppola          Al Pacino    Robert De Niro   
4            Sidney Lumet        Henry Fonda       Lee J. Cobb   
..                    ...                ...               ...   
458        Victor Fleming       George Cukor      Mervyn LeRoy   
459           Jean Renoir       Marcel Dalio       Nora Gregor   
460         W.S. Van Dyke     William Powell         Myrna Loy   
461       Lewis Milestone          Lew Ayres     Louis Wolheim   
462  Sergei M. Eisenstein  Aleksandr Antonov  Vladimir Barskiy   

                    Star3           Star4  No_of_Votes        Gross  
0              Bob Gunton  William Sadler      2343110   28,341,469  
1              James Caan    Diane Keaton      1620367  134,966,411  
2           Aaron Eckhart   Michael 

In [54]:
# Encontre todas as linhas onde uma coluna de categoria (Ex: cidade) contém um determinado valor (Ex: "São Paulo"). 

column = "Series_Title"

df[df[column].str.contains("Godfather")]

Poster_Link  \
1    https://m.media-amazon.com/images/M/MV5BM2MyNj...   
3    https://m.media-amazon.com/images/M/MV5BMWMwMG...   
974  https://m.media-amazon.com/images/M/MV5BNWFlYW...   

                Series_Title Released_Year Certificate  Runtime         Genre  \
1              The Godfather          1972           A  175 min  Crime, Drama   
3     The Godfather: Part II          1974           A  202 min  Crime, Drama   
974  The Godfather: Part III          1990           A  162 min  Crime, Drama   

     IMDB_Rating                                           Overview  \
1            9.2  An organized crime dynasty's aging patriarch t...   
3            9.0  The early life and career of Vito Corleone in ...   
974          7.6  Follows Michael Corleone, now in his 60s, as h...   

     Meta_score              Director          Star1           Star2  \
1         100.0  Francis Ford Coppola  Marlon Brando       Al Pacino   
3          90.0  Francis Ford Coppola      Al Pacino  Robert De Niro   
974        60.0  Francis Ford Coppola      Al Pacino    Diane Keaton   

             Star3         Star4  No_of_Votes        Gross  
1       James Caan  Diane Keaton      1620367  134,966,411  
3    Robert Duvall  Diane Keaton      1129952   57,300,000  
974    Andy Garcia   Talia Shire       359809   66,666,062

In [ ]:
'''
Adicione uma coluna nova que seja a diferença entre duas colunas (Ex: valor_original - desconto).
* Adapatado para a diferença entre a média de IMDB_Rating e Meta_score
'''

df["Mean_score"] = (((df["Meta_score"]/10) + df["IMDB_Rating"])/2)
df 

Poster_Link  \
0    https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1    https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2    https://m.media-amazon.com/images/M/MV5BMTMxNT...   
3    https://m.media-amazon.com/images/M/MV5BMWMwMG...   
4    https://m.media-amazon.com/images/M/MV5BMWU4N2...   
..                                                 ...   
995  https://m.media-amazon.com/images/M/MV5BNGEwMT...   
996  https://m.media-amazon.com/images/M/MV5BODk3Yj...   
997  https://m.media-amazon.com/images/M/MV5BM2U3Yz...   
998  https://m.media-amazon.com/images/M/MV5BZTBmMj...   
999  https://m.media-amazon.com/images/M/MV5BMTY5OD...   

                 Series_Title Released_Year Certificate  Runtime  \
0    The Shawshank Redemption          1994           A  142 min   
1               The Godfather          1972           A  175 min   
2             The Dark Knight          2008          UA  152 min   
3      The Godfather: Part II          1974           A  202 min   
4                12 Angry Men          1957           U   96 min   
..                        ...           ...         ...      ...   
995    Breakfast at Tiffany's          1961           A  115 min   
996                     Giant          1956           G  201 min   
997     From Here to Eternity          1953      Passed  118 min   
998                  Lifeboat          1944         NaN   97 min   
999              The 39 Steps          1935         NaN   86 min   

                        Genre  IMDB_Rating  \
0                       Drama          9.3   
1                Crime, Drama          9.2   
2        Action, Crime, Drama          9.0   
3                Crime, Drama          9.0   
4                Crime, Drama          9.0   
..                        ...          ...   
995    Comedy, Drama, Romance          7.6   
996            Drama, Western          7.6   
997       Drama, Romance, War          7.6   
998                Drama, War          7.6   
999  Crime, Mystery, Thriller          7.6   

                                              Overview  Meta_score  \
0    Two imprisoned men bond over a number of years...        80.0   
1    An organized crime dynasty's aging patriarch t...       100.0   
2    When the menace known as the Joker wreaks havo...        84.0   
3    The early life and career of Vito Corleone in ...        90.0   
4    A jury holdout attempts to prevent a miscarria...        96.0   
..                                                 ...         ...   
995  A young New York socialite becomes interested ...        76.0   
996  Sprawling epic covering the life of a Texas ca...        84.0   
997  In Hawaii in 1941, a private is cruelly punish...        85.0   
998  Several survivors of a torpedoed merchant ship...        78.0   
999  A man in London tries to help a counter-espion...        93.0   

                 Director              Star1              Star2  \
0          Frank Darabont        Tim Robbins     Morgan Freeman   
1    Francis Ford Coppola      Marlon Brando          Al Pacino   
2       Christopher Nolan     Christian Bale       Heath Ledger   
3    Francis Ford Coppola          Al Pacino     Robert De Niro   
4            Sidney Lumet        Henry Fonda        Lee J. Cobb   
..                    ...                ...                ...   
995         Blake Edwards     Audrey Hepburn     George Peppard   
996        George Stevens   Elizabeth Taylor        Rock Hudson   
997        Fred Zinnemann     Burt Lancaster   Montgomery Clift   
998      Alfred Hitchcock  Tallulah Bankhead        John Hodiak   
999      Alfred Hitchcock       Robert Donat  Madeleine Carroll   

              Star3           Star4  No_of_Votes        Gross  Difference  \
0        Bob Gunton  William Sadler      2343110   28,341,469   2343100.7   
1        James Caan    Diane Keaton      1620367  134,966,411   1620357.8   
2     Aaron Eckhart   Michael Caine      2303232  534,858,444   2303223.0   
3     Robert Duvall   

In [59]:
# Crie uma coluna categórica baseada em faixas (Ex: “baixo”, “médio”, “alto” para diferentes intervalos de preço). 

df["Rating_category"] = pd.cut(df["IMDB_Rating"], bins=[0, 5, 7, 10], labels=["baixo", "médio", "alto"])
df

Poster_Link  \
0    https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1    https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2    https://m.media-amazon.com/images/M/MV5BMTMxNT...   
3    https://m.media-amazon.com/images/M/MV5BMWMwMG...   
4    https://m.media-amazon.com/images/M/MV5BMWU4N2...   
..                                                 ...   
995  https://m.media-amazon.com/images/M/MV5BNGEwMT...   
996  https://m.media-amazon.com/images/M/MV5BODk3Yj...   
997  https://m.media-amazon.com/images/M/MV5BM2U3Yz...   
998  https://m.media-amazon.com/images/M/MV5BZTBmMj...   
999  https://m.media-amazon.com/images/M/MV5BMTY5OD...   

                 Series_Title Released_Year Certificate  Runtime  \
0    The Shawshank Redemption          1994           A  142 min   
1               The Godfather          1972           A  175 min   
2             The Dark Knight          2008          UA  152 min   
3      The Godfather: Part II          1974           A  202 min   
4                12 Angry Men          1957           U   96 min   
..                        ...           ...         ...      ...   
995    Breakfast at Tiffany's          1961           A  115 min   
996                     Giant          1956           G  201 min   
997     From Here to Eternity          1953      Passed  118 min   
998                  Lifeboat          1944         NaN   97 min   
999              The 39 Steps          1935         NaN   86 min   

                        Genre  IMDB_Rating  \
0                       Drama          9.3   
1                Crime, Drama          9.2   
2        Action, Crime, Drama          9.0   
3                Crime, Drama          9.0   
4                Crime, Drama          9.0   
..                        ...          ...   
995    Comedy, Drama, Romance          7.6   
996            Drama, Western          7.6   
997       Drama, Romance, War          7.6   
998                Drama, War          7.6   
999  Crime, Mystery, Thriller          7.6   

                                              Overview  Meta_score  \
0    Two imprisoned men bond over a number of years...        80.0   
1    An organized crime dynasty's aging patriarch t...       100.0   
2    When the menace known as the Joker wreaks havo...        84.0   
3    The early life and career of Vito Corleone in ...        90.0   
4    A jury holdout attempts to prevent a miscarria...        96.0   
..                                                 ...         ...   
995  A young New York socialite becomes interested ...        76.0   
996  Sprawling epic covering the life of a Texas ca...        84.0   
997  In Hawaii in 1941, a private is cruelly punish...        85.0   
998  Several survivors of a torpedoed merchant ship...        78.0   
999  A man in London tries to help a counter-espion...        93.0   

                 Director              Star1              Star2  \
0          Frank Darabont        Tim Robbins     Morgan Freeman   
1    Francis Ford Coppola      Marlon Brando          Al Pacino   
2       Christopher Nolan     Christian Bale       Heath Ledger   
3    Francis Ford Coppola          Al Pacino     Robert De Niro   
4            Sidney Lumet        Henry Fonda        Lee J. Cobb   
..                    ...                ...                ...   
995         Blake Edwards     Audrey Hepburn     George Peppard   
996        George Stevens   Elizabeth Taylor        Rock Hudson   
997        Fred Zinnemann     Burt Lancaster   Montgomery Clift   
998      Alfred Hitchcock  Tallulah Bankhead        John Hodiak   
999      Alfred Hitchcock       Robert Donat  Madeleine Carroll   

              Star3           Star4  No_of_Votes        Gross  Difference  \
0        Bob Gunton  William Sadler      2343110   28,341,469   2343100.7   
1        James Caan    Diane Keaton      1620367  134,966,411   1620357.8   
2     Aaron Eckhart   Michael Caine      2303232  534,858,444   2303223.0   
3     Robert Duvall   

In [61]:
# Ordene o DataFrame por uma coluna numérica em ordem decrescente e redefina o índice. 

df.sort_values("IMDB_Rating", ascending=False, inplace=True) 
df.reset_index(drop=True, inplace=True) 
df

Poster_Link  \
0    https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1    https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2    https://m.media-amazon.com/images/M/MV5BMWMwMG...   
3    https://m.media-amazon.com/images/M/MV5BMWU4N2...   
4    https://m.media-amazon.com/images/M/MV5BMTMxNT...   
..                                                 ...   
995  https://m.media-amazon.com/images/M/MV5BNGEwMT...   
996  https://m.media-amazon.com/images/M/MV5BODk3Yj...   
997  https://m.media-amazon.com/images/M/MV5BM2U3Yz...   
998  https://m.media-amazon.com/images/M/MV5BZTBmMj...   
999  https://m.media-amazon.com/images/M/MV5BMTY5OD...   

                 Series_Title Released_Year Certificate  Runtime  \
0    The Shawshank Redemption          1994           A  142 min   
1               The Godfather          1972           A  175 min   
2      The Godfather: Part II          1974           A  202 min   
3                12 Angry Men          1957           U   96 min   
4             The Dark Knight          2008          UA  152 min   
..                        ...           ...         ...      ...   
995    Breakfast at Tiffany's          1961           A  115 min   
996                     Giant          1956           G  201 min   
997     From Here to Eternity          1953      Passed  118 min   
998                  Lifeboat          1944         NaN   97 min   
999              The 39 Steps          1935         NaN   86 min   

                        Genre  IMDB_Rating  \
0                       Drama          9.3   
1                Crime, Drama          9.2   
2                Crime, Drama          9.0   
3                Crime, Drama          9.0   
4        Action, Crime, Drama          9.0   
..                        ...          ...   
995    Comedy, Drama, Romance          7.6   
996            Drama, Western          7.6   
997       Drama, Romance, War          7.6   
998                Drama, War          7.6   
999  Crime, Mystery, Thriller          7.6   

                                              Overview  Meta_score  \
0    Two imprisoned men bond over a number of years...        80.0   
1    An organized crime dynasty's aging patriarch t...       100.0   
2    The early life and career of Vito Corleone in ...        90.0   
3    A jury holdout attempts to prevent a miscarria...        96.0   
4    When the menace known as the Joker wreaks havo...        84.0   
..                                                 ...         ...   
995  A young New York socialite becomes interested ...        76.0   
996  Sprawling epic covering the life of a Texas ca...        84.0   
997  In Hawaii in 1941, a private is cruelly punish...        85.0   
998  Several survivors of a torpedoed merchant ship...        78.0   
999  A man in London tries to help a counter-espion...        93.0   

                 Director              Star1              Star2  \
0          Frank Darabont        Tim Robbins     Morgan Freeman   
1    Francis Ford Coppola      Marlon Brando          Al Pacino   
2    Francis Ford Coppola          Al Pacino     Robert De Niro   
3            Sidney Lumet        Henry Fonda        Lee J. Cobb   
4       Christopher Nolan     Christian Bale       Heath Ledger   
..                    ...                ...                ...   
995         Blake Edwards     Audrey Hepburn     George Peppard   
996        George Stevens   Elizabeth Taylor        Rock Hudson   
997        Fred Zinnemann     Burt Lancaster   Montgomery Clift   
998      Alfred Hitchcock  Tallulah Bankhead        John Hodiak   
999      Alfred Hitchcock       Robert Donat  Madeleine Carroll   

              Star3           Star4  No_of_Votes        Gross  Difference  \
0        Bob Gunton  William Sadler      2343110   28,341,469   2343100.7   
1        James Caan    Diane Keaton      1620367  134,966,411   1620357.8   
2     Robert Duvall    Diane Keaton      1129952   57,300,000   1129943.0   
3     Martin Balsam   

In [62]:
# Ordene por duas colunas ao mesmo tempo (Ex: primeiro por "cidade", depois por "total de vendas")

df.sort_values(["IMDB_Rating", "Meta_score"], ascending=[False, False], inplace=True) 
df.reset_index(drop=True, inplace=True)
df

Poster_Link  \
0    https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1    https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2    https://m.media-amazon.com/images/M/MV5BMWU4N2...   
3    https://m.media-amazon.com/images/M/MV5BMWMwMG...   
4    https://m.media-amazon.com/images/M/MV5BMTMxNT...   
..                                                 ...   
995  https://m.media-amazon.com/images/M/MV5BMTU0Nz...   
996  https://m.media-amazon.com/images/M/MV5BODNiZm...   
997  https://m.media-amazon.com/images/M/MV5BNGMxZj...   
998  https://m.media-amazon.com/images/M/MV5BMjI2OD...   
999  https://m.media-amazon.com/images/M/MV5BMzc0Zm...   

                 Series_Title Released_Year Certificate  Runtime  \
0    The Shawshank Redemption          1994           A  142 min   
1               The Godfather          1972           A  175 min   
2                12 Angry Men          1957           U   96 min   
3      The Godfather: Part II          1974           A  202 min   
4             The Dark Knight          2008          UA  152 min   
..                        ...           ...         ...      ...   
995              Seven Pounds          2008          UA  123 min   
996      The Butterfly Effect          2004           U  113 min   
997                 El cuerpo          2012         NaN  112 min   
998                 Celda 211          2009         NaN  113 min   
999                 Die Welle          2008         NaN  107 min   

                        Genre  IMDB_Rating  \
0                       Drama          9.3   
1                Crime, Drama          9.2   
2                Crime, Drama          9.0   
3                Crime, Drama          9.0   
4        Action, Crime, Drama          9.0   
..                        ...          ...   
995                     Drama          7.6   
996   Drama, Sci-Fi, Thriller          7.6   
997         Mystery, Thriller          7.6   
998  Action, Adventure, Crime          7.6   
999           Drama, Thriller          7.6   

                                              Overview  Meta_score  \
0    Two imprisoned men bond over a number of years...        80.0   
1    An organized crime dynasty's aging patriarch t...       100.0   
2    A jury holdout attempts to prevent a miscarria...        96.0   
3    The early life and career of Vito Corleone in ...        90.0   
4    When the menace known as the Joker wreaks havo...        84.0   
..                                                 ...         ...   
995  A man with a fateful secret embarks on an extr...        36.0   
996  Evan Treborn suffers blackouts during signific...        30.0   
997  A detective searches for the body of a femme f...         NaN   
998  The story of two men on different sides of a p...         NaN   
999  A high school teacher's experiment to demonstr...         NaN   

                 Director             Star1           Star2            Star3  \
0          Frank Darabont       Tim Robbins  Morgan Freeman       Bob Gunton   
1    Francis Ford Coppola     Marlon Brando       Al Pacino       James Caan   
2            Sidney Lumet       Henry Fonda     Lee J. Cobb    Martin Balsam   
3    Francis Ford Coppola         Al Pacino  Robert De Niro    Robert Duvall   
4       Christopher Nolan    Christian Bale    Heath Ledger    Aaron Eckhart   
..                    ...               ...             ...              ...   
995      Gabriele Muccino        Will Smith  Rosario Dawson  Woody Harrelson   
996            Eric Bress  J. Mackye Gruber  Ashton Kutcher        Amy Smart   
997           Oriol Paulo     Jose Coronado      Hugo Silva      Belén Rueda   
998         Daniel Monzón        Luis Tosar  Alberto Ammann  Antonio Resines   
999         Dennis Gansel      Jürgen Vogel   Frederick Lau      Max Riemelt   

               Star4  No_of_Votes        Gross  Difference  Mean_score  \
0     William Sadler      2343110   28,341,469   2343100.7        8.65   
1       Diane Keaton      